name              'yum-centos'
maintainer        'Chef Software, Inc.'
maintainer_email  'cookbooks@chef.io'
license           'Apache-2.0'
description       'Installs and configures the Centos Yum repositories'
version           '5.0.0'
source_url        'https://github.com/chef-cookbooks/yum-centos'
issues_url        'https://github.com/chef-cookbooks/yum-centos/issues'
chef_version      '>= 12.15'

supports 'centos'
