name              'yum-centos'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures the Centos Yum repositories'
version           '5.2.9'
source_url        'https://github.com/sous-chefs/yum-centos'
issues_url        'https://github.com/sous-chefs/yum-centos/issues'
chef_version      '>= 12.15'

supports 'centos'
